---
- name: Stop PHD Daemons
  command: chdir=/var/www/phabricator/ ./bin/phd stop

- name: Clone libphutil
  git: repo=git://github.com/facebook/libphutil dest=/var/www/libphutil

- name: Clone arcanist
  git: repo=git://github.com/facebook/arcanist dest=/var/www/arcanist

- name: Clone phabricator
  git: repo=git://github.com/facebook/phabricator dest=/var/www/phabricator

- name: Migrate the database
  command: chdir=/var/www/phabricator/ ./bin/storage upgrade --force

- name: Start PHD daemons
  command: chdir=/var/www/phabricator ./bin/phd start
