---
- name: Install nginx
  yum: name=nginx state=present

- name: Autostart nginx
  command: chkconfig nginx on

- name: Copy nginx config
  template: src=phabricator.conf dest=/etc/nginx/conf.d/{{ domain }}.conf
  notify: restart nginx